package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/cunex-club/quickattend-backend/internal/infrastructure/http/handler/graphql/model"
	"github.com/google/uuid"
)

// RegistrationSummary is the resolver for the registrationSummary field.
func (r *queryResolver) RegistrationSummary(ctx context.Context, eventID string) (*model.RegistrationSummary, error) {
	parsedEventID, err := uuid.Parse(eventID)
	if err != nil {
		return nil, fmt.Errorf("invalid event id: %w", err)
	}

	data, err := r.Service.Dashboard.GetRegistrationSummary(ctx, parsedEventID)
	if err != nil {
		return nil, err
	}

	return &model.RegistrationSummary{
		TotalEligible: data.TotalEligible,
		TotalStudent:  data.TotalStudent,
		TotalStaff:    data.TotalStaff,
		TotalAll:      data.TotalAll,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
