package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/cunex-club/quickattend-backend/internal/infrastructure/http/handler/graphql/model"
	"github.com/google/uuid"
)

// EventDashboardData is the resolver for the eventDashboardData field.
func (r *queryResolver) EventDashboardData(ctx context.Context, eventID string) (*model.EventDashboard, error) {
	parsedEventID, err := uuid.Parse(eventID)
	if err != nil {
		return nil, fmt.Errorf("invalid event id: %w", err)
	}

	data, err := r.Service.Dashboard.GetEventDashboardData(ctx, parsedEventID)
	if err != nil {
		return nil, err
	}

	orgStats := make([]*model.OrganizationStat, 0, len(data.OrganizationStats))
	for _, item := range data.OrganizationStats {
		orgStats = append(orgStats, &model.OrganizationStat{
			Organization: item.Organization,
			StudentCount: item.StudentCount,
			StaffCount:   item.StaffCount,
			TotalCount:   item.TotalCount,
		})
	}

	timeSeriesStats := make([]*model.TimeStat, 0, len(data.TimeSeriesStats))
	for _, item := range data.TimeSeriesStats {
		timeSeriesStats = append(timeSeriesStats, &model.TimeStat{
			TimeBucket:   item.TimeBucket,
			StudentCount: item.StudentCount,
			StaffCount:   item.StaffCount,
			TotalCount:   item.TotalCount,
		})
	}

	return &model.EventDashboard{
		Summary: &model.RegistrationSummary{
			TotalEligible: data.Summary.TotalEligible,
			TotalStudent:  data.Summary.TotalStudent,
			TotalStaff:    data.Summary.TotalStaff,
			TotalAll:      data.Summary.TotalAll,
		},
		OrganizationStats: orgStats,
		TimeSeriesStats:   timeSeriesStats,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
